# Generated by Django 4.1.6 on 2023-02-09 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="primary_img",
            new_name="primary_image",
        ),
    ]
