# Generated by Django 4.1.6 on 2023-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_primary_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="primary_image",
            field=models.FileField(default="default.jpg", upload_to="primary_images"),
        ),
    ]
