# Generated by Django 4.1.6 on 2023-02-23 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_alter_coupon_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.CharField(
                help_text="Between 1 to 100 percent",
                max_length=3,
                validators=[
                    django.core.validators.MinLengthValidator(0),
                    django.core.validators.MaxLengthValidator(100),
                ],
            ),
        ),
    ]
