# Generated by Django 4.1.6 on 2023-02-23 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0003_alter_coupon_discount"),
        ("orders", "0004_location_alter_order_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="coupons.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.CharField(
                default=0,
                max_length=3,
                validators=[
                    django.core.validators.MinLengthValidator(0),
                    django.core.validators.MaxLengthValidator(100),
                ],
            ),
        ),
    ]
